### ISSUE TITLE
Remove any duplicates

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/reading-list#16]
An entry should only appear once in the entire list, this is a good hacktoberfest issue and will be tagged as such.

**Comment by seixasfelipe** [comment]
I'll take this one. 
The only solution that came in my head is to have a simple cmd program to check the README.md file.

Do you have any other idea in mind?

**Comment by mattjegan** [comment]
I was appealing to a more manual solution of just getting everyone to keep an eye on the list, but a script that could run on each PR would be awesome. Not sure how we'd get that working though, we'd need some sort of CI set up as well I think.
